name: StyleSelect
author: kunambi
category: Forms
tags: [select, form]
current: v1.4
copyright: "Thomas Kunambi, 23 Critters"
description: Style Select is a nifty widget that allows you to style a SELECT box with CSS
